### ISSUE TITLE
요청 사항

### ISSUE THREAD

**Issue by Wollala** [Wollala/wollala-upbit#10]
@SungHwaJung 님 요청사항

1.  다만 수익률 표시란의 평가금액에 있어서 거래화폐 종류가 KRW가 아닌 BTC인 경우 공란으로 표시되어 총평가금이 그만큼 적게 표시되고 있습니다. USDT도 마찬가지 일런지는 저가 보유한 것이 없어서 확인은 해보지 못하였습니다.

2. 그리고 Tiker filter에 USDT항목이 필요하지는 않을런지요.

**Comment by Wollala** [comment]
1. 확인 해보니 잘 동작하는 것 같습니다. 
2. USDT는 거래량이 가장 큰 화폐가 BTC인데 하루 거래량이 BTC/USDT기준 3억 미만이라...크게 적용의 필요성을 못느끼고 있습니다.

**Comment by SUNGHWAJUNG** [comment]
감사합니다.
수고 많으셨습니다.
