### ISSUE TITLE
거래내역 불러오기 기간 설정에서 2019년 이전은 선택할 수가 없습니다.

### ISSUE THREAD

**Issue by undersense** [Wollala/wollala-upbit#14]
너무 많은 거래내역을 업비트 거래내역에서 불러내기가 너무 힘들고 오래 걸렸는데
이 앱을 통하니 정말 쉬워졌습니다. 그런데 몇 몇 제약 사항이 있어 활용이 조금 어렵네요.

사용상 이슈가 있어서 남겨봅니다.
1. 거래내역 불러오기 기간 설정에서 2019년 이전은 선택할 수가 없습니다.
2, 업비트 거래내역과 앱 상의 거래내역 폼이 조금 달라 불러온 거래내역을 복사해서 업비트 거래내역 폼을 기초로 만든 엑셀에 붙여넣어 처리하기가 조금 어렵네요.
-> 단순하게 업비트 거래내역을 api 를 통해서 불러올 수 있게만 하는 기능만 있어도 너무 좋을 것 같습니다.
그 내역만 쉽게 불러올 수 있으면 엑셀을 통해서 다양하게 처리해서 활용할 수 있을 것 같습니다.

**Comment by Wollala** [comment]
@undersense  
답변이 늦었습니다. 말씀해주신 Comment 참고 하여 업데이트 하겠습니다
