### ISSUE TITLE
안녕하세요! 염치불구하고 질문하나 드립니다 ㅠㅠ

### ISSUE THREAD

**Issue by ChangHoonKang** [Wollala/wollala-upbit#16]
개발자님께서 만드신 거래내역을 사용하려고 하는데 IP주소는 어떤 값을 입력해야 올바른 API Key를 받을 수 있을까요?

**Comment by Wollala** [comment]
해당 프로그램을 사용하는 컴퓨터의 IP주소를 입력하시면 됩니다.
https://www.findip.kr/
이 링크 들어가보세요
