### ISSUE TITLE
암호화폐 별 수익률 표시

### ISSUE THREAD

**Issue by Wollala** [Wollala/wollala-upbit#5]
암호화폐 별 수익률 표시하는 화면 구현.

새로운 탭을 만들고 그곳에 구현하면 될 듯, 
이슈 사항은 upbit내에서만 이루어진 거래가 아닌 상황 어떻게 처리할지 고민해야 보아야함.

예를 들면 일정 기간 upbit 내에서 거래를 하다가 다른 거래소로 출금을 했다던지.. 다른 거래소에서 입금이 되었다던지...
출금시 매수만 하고 매도 기록이 없어.. 수익률 판단이 어려움.

- 출금 요청시간의 가격을 매도 가격으로?

입금시 매수 기록은 없는데 수량은 있음.

- 입금시간의 가격을 매수 가격으로?

**Comment by SUNGHWAJUNG** [comment]
엑셀로 거래장부를 만들어 보려고 인터넷으로 xlwings를 공부하다 보니 우연히 귀중한 프로그램을 접하게 되었습니다.
더 이상 공부하지 않아도 이 프로그램을 사용하면 될 것 같습니다.

1. 다만 수익률 표시란의 평가금액에 있어서 거래화폐 종류가 KRW가 아닌 BTC인 경우 공란으로 표시되어 총평가금이 그만큼 적게 표시되고 있습니다. USDT도 마찬가지 일런지는 저가 보유한 것이 없어서 확인은 해보지 못하였습니다.
2. 그리고 Tiker filter에 USDT항목이 필요하지는 않을런지요.

수고스럽게 만들어 주신 프로그램을 잘 사용하도록 하겠습니다.
감사합니다.......

**Comment by Wollala** [comment]
> 엑셀로 거래장부를 만들어 보려고 인터넷으로 xlwings를 공부하다 보니 우연히 귀중한 프로그램을 접하게 되었습니다. 더 이상 공부하지 않아도 이 프로그램을 사용하면 될 것 같습니다.
> 
> 1. 다만 수익률 표시란의 평가금액에 있어서 거래화폐 종류가 KRW가 아닌 BTC인 경우 공란으로 표시되어 총평가금이 그만큼 적게 표시되고 있습니다. USDT도 마찬가지 일런지는 저가 보유한 것이 없어서 확인은 해보지 못하였습니다.
> 2. 그리고 Tiker filter에 USDT항목이 필요하지는 않을런지요.
> 
> 수고스럽게 만들어 주신 프로그램을 잘 사용하도록 하겠습니다. 감사합니다.......

아래 링크에서 처리하겠습니다
https://github.com/Wollala/wollala-upbit/issues/10
